# Generated by Django 3.0.7 on 2020-07-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Into_General_Suppliers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
