# Generated by Django 3.0.7 on 2020-07-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Into_General_Suppliers', '0003_service_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_card',
            name='service_card',
            field=models.FileField(blank=True, null=True, upload_to='slide_images'),
        ),
    ]
