# Generated by Django 3.0.7 on 2020-07-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Into_General_Suppliers', '0004_auto_20200724_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_card',
            name='service_card',
        ),
        migrations.AddField(
            model_name='service_card',
            name='electricity',
            field=models.ImageField(default='default.jpg', upload_to='slide_images'),
        ),
        migrations.AddField(
            model_name='service_card',
            name='extentions',
            field=models.ImageField(default='default.jpg', upload_to='slide_images'),
        ),
        migrations.AddField(
            model_name='service_card',
            name='flooring',
            field=models.ImageField(default='default.jpg', upload_to='slide_images'),
        ),
        migrations.AddField(
            model_name='service_card',
            name='painting',
            field=models.ImageField(default='default.jpg', upload_to='slide_images'),
        ),
        migrations.AddField(
            model_name='service_card',
            name='paving',
            field=models.ImageField(default='default.jpg', upload_to='slide_images'),
        ),
        migrations.AddField(
            model_name='service_card',
            name='plumbing',
            field=models.ImageField(default='default.jpg', upload_to='slide_images'),
        ),
        migrations.AddField(
            model_name='service_card',
            name='renovations',
            field=models.ImageField(default='default.jpg', upload_to='slide_images'),
        ),
        migrations.AddField(
            model_name='service_card',
            name='roofing',
            field=models.ImageField(default='default.jpg', upload_to='slide_images'),
        ),
        migrations.AddField(
            model_name='service_card',
            name='walling',
            field=models.ImageField(default='default.jpg', upload_to='slide_images'),
        ),
    ]
