# Generated by Django 3.0.7 on 2020-07-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Into_General_Suppliers', '0005_auto_20200724_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_card',
            name='content',
        ),
        migrations.RemoveField(
            model_name='service_card',
            name='title',
        ),
    ]
