# Generated by Django 3.0.7 on 2020-07-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Into_General_Suppliers', '0009_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_client',
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='custom@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='last_Name',
            field=models.CharField(default='name', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(default='name', max_length=1000),
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
