# Generated by Django 3.0.7 on 2020-07-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Into_General_Suppliers', '0010_auto_20200725_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default='name', max_length=1000),
        ),
    ]
