# Generated by Django 3.0.7 on 2020-07-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Into_General_Suppliers', '0011_auto_20200725_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='last_Name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
