# Generated by Django 3.0.7 on 2020-08-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Into_General_Suppliers', '0012_auto_20200725_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_card',
            name='blumbing',
            field=models.ImageField(default='default.jpg', upload_to='slide_images'),
        ),
        migrations.AddField(
            model_name='service_card',
            name='blumbing_content',
            field=models.TextField(default='name', max_length=1000),
        ),
    ]
