# Generated by Django 3.0.7 on 2020-07-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliderpic', '0003_slider_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='logo',
            new_name='images',
        ),
    ]
