# Generated by Django 3.0.7 on 2020-07-24 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliderpic', '0007_services_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services_Card',
        ),
    ]
