# Generated by Django 3.0.7 on 2020-07-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliderpic', '0009_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='about_pic',
            new_name='contact_pic',
        ),
    ]
