# Generated by Django 3.0.7 on 2020-07-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliderpic', '0011_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project2',
            field=models.ImageField(default='default.jpg', upload_to='slide_images'),
        ),
    ]
