# Generated by Django 3.0.7 on 2020-07-25 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sliderpic', '0012_projects_project2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walling1', models.ImageField(default='default.jpg', upload_to='walling_images')),
                ('walling2', models.ImageField(default='default.jpg', upload_to='walling_images')),
                ('walling3', models.ImageField(default='default.jpg', upload_to='walling_images')),
                ('walling4', models.ImageField(default='default.jpg', upload_to='walling_images')),
                ('walling5', models.ImageField(default='default.jpg', upload_to='walling_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roofing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roofing1', models.ImageField(default='default.jpg', upload_to='roofing_images')),
                ('roofing2', models.ImageField(default='default.jpg', upload_to='roofing_images')),
                ('roofing3', models.ImageField(default='default.jpg', upload_to='roofing_images')),
                ('roofing4', models.ImageField(default='default.jpg', upload_to='roofing_images')),
                ('roofing5', models.ImageField(default='default.jpg', upload_to='roofing_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Renovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renovation1', models.ImageField(default='default.jpg', upload_to='renovation_images')),
                ('renovation2', models.ImageField(default='default.jpg', upload_to='renovation_images')),
                ('renovation3', models.ImageField(default='default.jpg', upload_to='renovation_images')),
                ('renovation4', models.ImageField(default='default.jpg', upload_to='renovation_images')),
                ('renovation5', models.ImageField(default='default.jpg', upload_to='renovation_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plumbing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plumbing1', models.ImageField(default='default.jpg', upload_to='plumbing_images')),
                ('plumbing2', models.ImageField(default='default.jpg', upload_to='plumbing_images')),
                ('plumbing3', models.ImageField(default='default.jpg', upload_to='plumbing_images')),
                ('plumbing4', models.ImageField(default='default.jpg', upload_to='plumbing_images')),
                ('plumbing5', models.ImageField(default='default.jpg', upload_to='plumbing_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paving', models.ImageField(default='default.jpg', upload_to='paving_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting1', models.ImageField(default='default.jpg', upload_to='painting_images')),
                ('painting2', models.ImageField(default='default.jpg', upload_to='painting_images')),
                ('painting3', models.ImageField(default='default.jpg', upload_to='painting_images')),
                ('painting4', models.ImageField(default='default.jpg', upload_to='painting_images')),
                ('painting5', models.ImageField(default='default.jpg', upload_to='painting_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flooring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flooring1', models.ImageField(default='default.jpg', upload_to='flooring_images')),
                ('flooring', models.ImageField(default='default.jpg', upload_to='flooring_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extention1', models.ImageField(default='default.jpg', upload_to='extention_images')),
                ('extention2', models.ImageField(default='default.jpg', upload_to='extention_images')),
                ('extention3', models.ImageField(default='default.jpg', upload_to='extention_images')),
                ('extention4', models.ImageField(default='default.jpg', upload_to='extention_images')),
                ('extention5', models.ImageField(default='default.jpg', upload_to='extention_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity1', models.ImageField(default='default.jpg', upload_to='electricity_images')),
                ('electricity2', models.ImageField(default='default.jpg', upload_to='electricity_images')),
                ('electricity3', models.ImageField(default='default.jpg', upload_to='electricity_images')),
                ('electricity4', models.ImageField(default='default.jpg', upload_to='electricity_images')),
                ('electricity5', models.ImageField(default='default.jpg', upload_to='electricity_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
