# Generated by Django 3.0.7 on 2020-07-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliderpic', '0013_electricity_extention_flooring_painting_paving_plumbing_renovation_roofing_walling'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_pic2',
            field=models.ImageField(default='default.jpg', upload_to='slide_images'),
        ),
    ]
