# Generated by Django 3.0.7 on 2020-08-17 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sliderpic', '0014_about_about_pic2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='About_Page',
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_Page',
        ),
        migrations.RenameModel(
            old_name='Slider',
            new_name='Home_Page',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Projects_Page',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Services_Page',
        ),
    ]
