# Generated by Django 3.0.7 on 2020-08-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliderpic', '0016_auto_20200817_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paving',
            old_name='paving',
            new_name='paving1',
        ),
        migrations.AddField(
            model_name='paving',
            name='paving2',
            field=models.ImageField(default='default.jpg', upload_to='paving_images'),
        ),
        migrations.AddField(
            model_name='paving',
            name='paving3',
            field=models.ImageField(default='default.jpg', upload_to='paving_images'),
        ),
        migrations.AddField(
            model_name='paving',
            name='paving4',
            field=models.ImageField(default='default.jpg', upload_to='paving_images'),
        ),
        migrations.AddField(
            model_name='paving',
            name='paving5',
            field=models.ImageField(default='default.jpg', upload_to='paving_images'),
        ),
    ]
